language: c
env:
  - RUN_TEST=true OCAML_VERSION=4.03.0
  - RUN_TEST=true OCAML_VERSION=4.03.0+flambda
  - RUN_TEST=true OCAML_VERSION=4.04.0
  - RUN_TEST=true OCAML_VERSION=4.04.0+flambda
  - RUN_TEST=true OCAML_VERSION=4.06.0
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
      - time
before_install:
  # Download and use opam2
  - wget -O ${HOME}/opam https://github.com/ocaml/opam/releases/download/2.0.0-beta6/opam-2.0.0-beta6-x86_64-linux
  - chmod +x ${HOME}/opam
  # Some opam boilerplate
  - export OPAMYES=1
  - export OPAMJOBS=2
  # Init opam, and the default switch with the right ocaml version
  - ${HOME}/opam init --compiler=${OCAML_VERSION}
  - eval `${HOME}/opam config env`
  - export OPAMVERBOSE=1
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
  - opam install ocamlfind jbuilder
  - if ${RUN_TEST}; then opam pin add dolmen https://github.com/Gbury/dolmen.git; fi
install:
  - make build
script:
  # Build and launch the tests
  - if [ "$TO_TEST" = "tests" ]; then make lib && make bin && make test; fi
  # Try and install the package with opam
  - if [ "$TO_TEST" = "install" ]; then ${HOME}/opam install msat.dev; fi

