#!/bin/bash

CURDIR=`dirname $0`
SOLVER="$CURDIR/../src/main/main.exe"

solvertest () {
    for f in `find -L $1 -type f -name '*.cnf' # -o -name '*.smt2'`
    do
        echo -ne "\r\033[KTesting $f..."
        "$SOLVER" -time 30s -size 1G -check $f | grep $2
        RET=$?
        if [ $RET -ne 0 ];
        then
            echo -e "\r\033[K\e[31m[KO]\e[0m $3 - $f"
            exit 2
        fi
    done
    echo -e "\r\033[K\e[32m[OK]\e[0m $3/$2"
}

echo "run benchmarks…"

solvertest "$CURDIR/sat/" "Sat" $1
solvertest "$CURDIR/unsat/" "Unsat" $1
