
sudoku17.txt:
	wget https://github.com/attractivechaos/plb/releases/download/v0/sudoku17.txt.gz -O sudoku17.txt.gz
	gunzip -f sudoku17.txt.gz

top50k.txt:
	wget https://github.com/attractivechaos/plb/releases/download/v0/sudoku.top50k.gz -O top50k.txt.gz
	gunzip -f top50k.txt.gz

fetch-all: sudoku17.txt top50k.txt
